### PR TITLE
feat: upgrade rc-util to 4.x

### PR DESCRIPTION
**Pull request by paranoidjk**
ref https://github.com/ant-design/ant-design-mobile/issues/959

### CODE REVIEW

**Comment by paranoidjk** [comment]
@yesmeck ci 怎么挂了

**Comment by yesmeck** [comment]
https://github.com/react-component/tree-select/commit/75f93024c7f2a183c1f488c8b983b7c947e41c0e

**Comment by paranoidjk** [comment]
@yesmeck 👌 ok了就发了patch吧

**Comment by yesmeck** [comment]
1.9.1

**Pull request merged**
