### PR TITLE
Add filterWait props

### PR DESCRIPTION
**Pull request by EscapeB**
Fix https://github.com/react-component/tree-select/issues/180

1. add filterWait props to support delay filter
2. rewrite some logic when filterTreeNode is false

### CODE REVIEW

**Comment by EscapeB** [comment]
@zombieJ Could you please review and merge this pr?

**Comment by zombieJ** [comment]
Could you help to create a PR with `master` branch? `2.9.x` is a maintenance branch which only accepts patch fix.

**Comment by EscapeB** [comment]
> Could you help to create a PR with `master` branch? `2.9.x` is a maintenance branch which only accepts patch fix.

OK, I will close this PR and reopen another.

**Comment by x-shron** [comment]
filterWait props is which version?

**Pull request closed without merging**
