### PR TITLE
Optimize node ancestor checks

### PR DESCRIPTION
**Pull request by tvasenin**
Eliminate String.split() and compare position strings directly.

Gives huge performance boost when handling lots of nodes, e.g.
https://react-component.github.io/tree-select/examples/big-data.html

### CODE REVIEW

**Comment by yesmeck** [comment]
Thanks!

**Comment by tvasenin** [comment]
@yesmeck I see that a new version of tree component (v1.7.9) has already been uploaded to NPM.

Could you, please, also release new tree-select component?

**Comment by yesmeck** [comment]
Released 1.12.1

**Comment by tvasenin** [comment]
@yesmeck could you please, also bump `rc-tree` dependency?
Should be `~1.7.9` (version with performance fix) instead of `~1.7.1`.

**Comment by yesmeck** [comment]
`rc-tree-select` will use `rc-tree@1.7.9` if you reinstall it ?

**Comment by tvasenin** [comment]
Yes, `npm update rc-tree-select` updates latest `rc-tree` too.

Still, for some reason, the example page uses old `rc-tree dependency for some reason`:

**Comment by yesmeck** [comment]
I'v just updated the example pages.

**Pull request merged**
